modLoader = "lowcodefml"
loaderVersion = "[40,)"
license = "GNU LGPL 3.0"
issueTrackerURL = "https://github.com/MayaqqDev/Jukeboxfix/issues"
[[mods]]
modId = "jukeboxfix"
version = "${version}"
displayName = "Jukeboxfix"
logoFile = "icon.png"
authors = "Mayaqq"
description = '''
Fixes disc duplication with stackable music discs
'''
[[dependencies.jukeboxfix]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.jukeboxfix]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"